# Settings for Bolt Article

# All options: blockcode, counter, icons, inlineformat, reorder, selector, specialchars, style, tags, underline, variable
default:
  plugins: [ blockcode, inlineformat, reorder, selector, style, tags, underline ]
  source: true

plugins:
  blockcode: [ blockcode/blockcode.min.js ]
  counter: [ counter/counter.min.js ]
  icons: [ icons/icons.min.js ]
  inlineformat: [ inlineformat/inlineformat.min.js ]
  reorder: [ reorder/reorder.min.js ]
  selector: [ selector/selector.min.js ]
  specialchars: [ specialchars/specialchars.min.js ]
  style: [ style/style.min.js ]
  tags: [ tags/tags.min.js, tags/tags.min.css ]
  underline: [ underline/underline.min.js ]
  variable: [ variable/variable.min.js ]